<a href="https://colab.research.google.com/github/kevintsi/deep_learning_course/blob/main/Intro_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TP movies

Question 1

In [2]:
import pandas as pds
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Question 2

In [3]:
def combine_features(tab):
  tab = [str(item) for item in tab]
  return ' '.join(tab)

In [4]:
combine_features(['keywords','cast','genres','director'])

'keywords cast genres director'

Question 3

In [5]:
url='https://drive.google.com/file/d/1bjg8Re6aMSXKYu3yqkO6KRFLwsa3GPM7/view?usp=sharing'
path ='https://drive.google.com/uc?export=download&id=' + url.split('/')[-2]
df = pds.read_csv(path)

Question 3

In [6]:
df.fillna(" ")

index  ...           director
0         0  ...      James Cameron
1         1  ...     Gore Verbinski
2         2  ...         Sam Mendes
3         3  ...  Christopher Nolan
4         4  ...     Andrew Stanton
...     ...  ...                ...
4798   4798  ...   Robert Rodriguez
4799   4799  ...       Edward Burns
4800   4800  ...        Scott Smith
4801   4801  ...        Daniel Hsia
4802   4802  ...   Brian Herzlinger

[4803 rows x 24 columns]

In [7]:
df.dtypes

index                     int64
budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
tagline                  object
title                    object
vote_average            float64
vote_count                int64
cast                     object
crew                     object
director                 object
dtype: object

In [8]:
for idx, row in df.iterrows():
  df.loc[idx,"combined_features"] = combine_features(row)

In [9]:
df.head()

index  ...                                  combined_features
0      0  ...  0 237000000 Action Adventure Fantasy Science F...
1      1  ...  1 300000000 Adventure Fantasy Action http://di...
2      2  ...  2 245000000 Action Adventure Crime http://www....
3      3  ...  3 250000000 Action Crime Drama Thriller http:/...
4      4  ...  4 260000000 Action Adventure Science Fiction h...

[5 rows x 25 columns]

Question 4

In [10]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df.combined_features)

print(cv.get_feature_names_out())
print(count_matrix.toarray())

['00' '000' '000126' ... '태극기' '해운대' '휘날리며']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Question 5

In [59]:
similarity_scores = cosine_similarity(count_matrix)
similarity_scores

array([[1.        , 0.93961627, 0.98638035, ..., 0.84699674, 0.40862149,
        0.64588589],
       [0.93961627, 1.        , 0.94576495, ..., 0.89714343, 0.45889093,
        0.68785228],
       [0.98638035, 0.94576495, 1.        , ..., 0.86059065, 0.41762716,
        0.65492255],
       ...,
       [0.84699674, 0.89714343, 0.86059065, ..., 1.        , 0.48187564,
        0.68078075],
       [0.40862149, 0.45889093, 0.41762716, ..., 0.48187564, 1.        ,
        0.4526639 ],
       [0.64588589, 0.68785228, 0.65492255, ..., 0.68078075, 0.4526639 ,
        1.        ]])

Question 6

In [26]:
def get_index_from_title(title: str) -> int:
    boolean_findings = df.title == title

    for i in range(len(boolean_findings)):
      if boolean_findings[i]:
        return i

    return None

In [28]:
get_index_from_title('Titanic')

25

In [60]:
titanic_similarity_scores = np.sort(similarity_scores[get_index_from_title('Titanic')])[::-1]
print(titanic_similarity_scores)
first_five_titanic_similarity_scores = mylist[:5]

[1.         0.97494403 0.97490701 ... 0.02464978 0.01817524 0.00375665]


In [56]:
first_five_titanic_similarity_scores

array([1.        , 0.97494403, 0.97490701, 0.97442447, 0.97437973])